version: '3.3'
services:
  test:
    build:
        context: ./
        dockerfile: Dockerfile
    tty: true
    ports:
      - "6800:6800"
      - "5000:5000"
    # volumes:
    #     - ./data/scrapyd:/work/scrapyd
    #     - ./data/scrapydweb:/work/scrapydweb